name: Picker Starter CI/CD

on:
  push:
    paths:
      - 'picker-starter/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Prettier
        run: yarn workspace picker-starter prettier
      - name: Lint
        run: yarn workspace picker-starter lint
      - name: Check types
        run: yarn workspace picker-starter check:types
      - name: Test
        run: yarn workspace picker-starter test
      - name: Build
        run: yarn workspace picker-starter build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Build
        run: yarn workspace picker-starter build
      - name: Deploy
        env:
          STORYBLOK_PERSONAL_ACCESS_TOKEN: ${{secrets.STORYBLOK_PERSONAL_ACCESS_TOKEN}}
        run: yarn workspace picker-starter deploy --skipPrompts
